def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.add_route('hello', 'hello')
    config.add_route('login', 'login')
    config.add_route('user_types', 'user_types')
    config.add_route('category_types', 'category_types')
    config.add_route('question_types', 'question_types')
    config.add_route('questions', 'questions')
    config.add_route('options', 'options')
    config.add_route('answers', 'answers')
    config.add_route('categories', 'categories')